version: "2"

services:

  frontend:
    image: "node:16"
    working_dir: "/var/www/app/frontend"
    volumes:
      - "./app/frontend2:/var/www/app/frontend"
    ports:
      - "${REACT_HTTP_PORT}:${REACT_HTTP_PORT}"
    expose:
      - "${REACT_HTTP_PORT}"
    command: "./start_dev.sh"
    env_file:
      - ./.env

  backend:
    image: "node:16"
    working_dir: "/var/www/app/backend"
    volumes:
      - "./app/backend:/var/www/app/backend"
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}"
    expose:
      - "${API_HTTP_PORT}"
    command: "./start_dev.sh"
    env_file:
      - ./.env