version: '3'

services:
  frontend:
    build:
      context: './app'
      dockerfile: './frontend/Dockerfile'
    ports:
      - '${REACT_DOCKER_PORT}:3000'
    env_file:
      - ./.env

  backend:
    build:
      context: './app'
      dockerfile: './backend/Dockerfile'
    ports:
      - '${API_DOCKER_PORT}:${API_HTTP_PORT}'
    env_file:
      - ./.env
